on:
  push:
    branches:
      - main
      - renovate/*
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - name: Install ShellCheck and shfmt
        run: |
          sudo apt-get update -y
          sudo apt-get install -y shellcheck shfmt

      - name: Run ShellCheck
        run: |
          shellcheck src/pre-commit

      - name: Run shfmt
        run: |
          shfmt -d -i 2 src/pre-commit

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - name: Install BATS
        run: |
          sudo apt-get update
          sudo apt-get install bats

      - name: Run BATS tests
        run: |
          bats test/pre-commit.bats
